### ISSUE TITLE
More info?

### ISSUE THREAD

**Issue by Toontje** [jacobsalmela/AdminLTE#6]
First i would like to thank you for this great piece of software. One issue i found with the web interface. There is no "More info" info. The link points to # which is undefined in the page.
```
<a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
```
Expected behaviour?

**Comment by jacobsalmela** [comment]
For now, this is expected; the "More Info" links are just placeholders until the [enhanced stats](https://github.com/jacobsalmela/AdminLTE/tree/historical-stats) are done.
