### ISSUE TITLE
Domains blocked is incorrect after adding IPv6 support

### ISSUE THREAD

**Issue by jacobsalmela** [jacobsalmela/AdminLTE#8]
Since the "amount of domains blocked" is read from `/etc/pihole/gravity.list`, the user may see twice as many domains as there really are since there are two lines for each domain (IPv4 and IPv6).

```
192.168.1.100 zz.zeroredirect1.com
2601:442:abcd:125:d833:f13e:6de6:4fa0 zz.zeroredirect1.com
```
It would probably be safer to just count the lines in `/etc/pihole/pihole.3.eventHorizon.txt `

**Comment by Mcat12** [comment]
Is this just a one line fix?

**Comment by jacobsalmela** [comment]
It should be.  We just need to change the path in the `index.php` code.  I'll be testing this out soon.
